default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/development.sqlite3

# Use sqlite3 in production by default.
production:
  <<: *default
  adapter: <%= ENV['DB_ADAPTER'] || 'sqlite3' %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  database: <%= ENV['DB_NAME'] || 'db/production/production.sqlite3' %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
